### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 16: ordinal not in range(128)

### ISSUE THREAD

**Issue by peileppe** [peileppe/cobe-journal#1]
program cobe-journal.py crashed with error : 

```
Traceback (most recent call last):
  File "cobe-journal.py", line 28, in <module>
    if __name__ == '__main__': main()
  File "cobe-journal.py", line 24, in main
    f.write("Tech> "+msg+"\n")
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 16: ordinal not in range(128)

```

**Comment by peileppe** [comment]
Locating the faulty character in sqlite : 

```
sqlite> select * from tokens where text like "%’%";
id|text|is_word
436|’|0

update tokens set text="'" where id=436;

```
